
spring:
  application:
    name: Backend
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8080
  servlet:
    context-path: /

firebase:
  bucket-name: cloudvault-456614
  image-url: https://storage.googleapis.com/${firebase.bucket-name}/%s

cors:
  allowed-origins: http://localhost:5173
  allowed-credentials: true
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  exposed-headers: "*"

gcp:
  project-id: cloudvault-456614
  bucket-name: cloudvault-456614
  credentials:
    location: D:/CloudVault/Backend/src/main/resources/service-account-key.json

logging:
  level:
    com.example.CloudVault: DEBUG
    com.google.cloud: DEBUG